favicon: images/icon.png

menu:
  日志[logs]: /
  规则[Rules]: /Rules
  记录器[Loggers]: /Loggers
  指令[Commands]: /Commands
  开发[Development]: /Development
  下载[Download]: /Download
  开源[Open Source]: /OpenSource

copyright:
  name: A Minecraft Server

license:
  name: LGPL-3.0
  url: https://choosealicense.com/licenses/lgpl-3.0/

rss:
  path: https://mcams.club/

mathjax:
  enable: false

katex:
  enable: false

utterances:
  enable: false
  repo: owner/repo
  issueTerm: pathname
  theme: github-light

analytics:
  enable: false
  gtag: G-XXXXXXXXXXXX
 
canvas_nest:
  enable: false
  color: '0，0，0'
  pointColor: '0，0，0'
  opacity: '0.8'
  count: '99'
  zIndex: '-1'
