favicon: images/icon.png

menu:
  发布[Release]: /
  规则[Rules]: /Rules
  指令[Commands]: /Commands
  开发[Development]: /Development

copyright:
  name: A Minecraft Server

license:
  name: LGPL-3.0
  url: https://choosealicense.com/licenses/lgpl-3.0/

rss:
  path: https://mcams.club/

mathjax:
  enable: false

katex:
  enable: true

utterances:
  enable: true
  repo: owner/repo
  issueTerm: pathname
  theme: github-light

analytics:
  enable: true
  gtag: G-XXXXXXXXXXXX